version: '3.7'

networks:
    backend:
        driver: bridge

services:
    redis:
        image: "redis:alpine"
        container_name: "vdg-redis-cache"
        restart: always
        expose:
            - "6379"
        networks:
            - default
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf
    proxy:
        image: nginx:alpine
        container_name: vdg-proxy
        ports:
        - '80:80'
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        restart: 'unless-stopped'
        networks:
        - backend
    server:
        build:
            context: ./
            target: development-build-stage
            dockerfile: Dockerfile
        container_name: vdg-server
        ports:
            - '4001:4001'
        env_file: .env.production.local
        volumes:
            - ./:/app
            - /app/node_modules
        restart: 'unless-stopped'
        networks:
            - backend
        depends_on:
            - redis
        links:
            - redis
        environment:
            - REDIS_URL=redis://vdg-redis-cache

volumes:
    redis-data:
    redis-conf:
    data:
        driver: local
