# Generated by Django 4.2.13 on 2024-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='app',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
