# Generated by Django 4.2.15 on 2024-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0002_auditlog_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='identifier',
            field=models.UUIDField(default=None, editable=False),
        ),
    ]
