# Generated by Django 4.2.13 on 2024-06-19 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
