# Generated by Django 4.2.14 on 2024-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_client_members_client_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
