# Generated by Django 4.2.14 on 2024-08-09 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0005_client_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_members',
            field=models.ManyToManyField(blank=True, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
