# Generated by Django 4.2.14 on 2024-08-12 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_alter_legislation_registration_requirements_and_more'),
        ('profiles', '0004_remove_profile_client'),
        ('client', '0007_client_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLegislationJobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrole', to='profiles.jobrole')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislation', to='navigator.legislation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
