# Generated by Django 4.2.14 on 2024-08-12 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_alter_legislation_registration_requirements_and_more'),
        ('client', '0008_clientlegislationjobrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_link', to='client.client')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislation_link', to='navigator.legislation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
