# Generated by Django 4.2.14 on 2024-08-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_alter_legislation_registration_requirements_and_more'),
        ('profiles', '0004_remove_profile_client'),
        ('client', '0009_clientlegislation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientlegislation',
            unique_together={('client', 'legislation')},
        ),
        migrations.AlterUniqueTogether(
            name='clientlegislationjobrole',
            unique_together={('client', 'legislation', 'job_role')},
        ),
    ]
