# Generated by Django 4.2.14 on 2024-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_alter_legislation_registration_requirements_and_more'),
        ('client', '0010_alter_clientlegislation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legislation_list',
            field=models.ManyToManyField(related_name='legislation_list', to='navigator.legislation'),
        ),
        migrations.DeleteModel(
            name='ClientLegislation',
        ),
    ]
