# Generated by Django 4.2.14 on 2024-08-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_client_legislation_list_delete_clientlegislation'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='starting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
