# Generated by Django 4.2.15 on 2024-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_settings',
            field=models.CharField(blank=True, choices=[('PwC', 'PwC'), ('Asics', 'Asics')], max_length=52, null=True),
        ),
    ]
