# Generated by Django 4.2.14 on 2024-08-22 08:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.BinaryField(default=None, null=True, validators=[core.validators.validate_image_extension]),
        ),
    ]
