# Generated by Django 4.2.14 on 2024-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0008_legislationjobrole_non_compliance_risk'),
        ('client', '0014_client_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legislation_list',
            field=models.ManyToManyField(blank=True, related_name='legislation_list', to='navigator.legislation'),
        ),
    ]
