# Generated by Django 4.2.15 on 2024-08-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_client_client_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_settings',
            new_name='sso_settings',
        ),
    ]
