# Generated by Django 4.2.15 on 2024-08-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_client_legislation_list'),
        ('client', '0015_rename_client_settings_client_sso_settings'),
    ]

    operations = [
    ]
