# Generated by Django 4.2.15 on 2024-08-29 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0016_merge_20240828_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
