# Generated by Django 4.2.15 on 2024-09-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0021_alter_registrationrequirement_legislation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0017_alter_client_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_owner_list',
            field=models.ManyToManyField(blank=True, related_name='project_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_legislations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.legislation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_legislations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('client', 'legislation')},
            },
        ),
    ]
