# Generated by Django 4.2.15 on 2024-09-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_client_project_owner_list_clientlegislation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='legislation_list',
        ),
    ]
