# Generated by Django 4.2.16 on 2024-10-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_remove_client_legislation_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlegislation',
            old_name='is_approved',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='clientlegislation',
            old_name='approval_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='clientlegislation',
            old_name='approved_by',
            new_name='published_by',
        ),
    ]
