# Generated by Django 4.2.16 on 2024-10-18 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0020_rename_is_approved_clientlegislation_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlegislation',
            name='retracted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retracted_legislations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientlegislation',
            name='retraction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
