version: "3.6"

networks:
    default:
        driver: bridge

services:
    redis:
        image: "redis:alpine"
        container_name: "redis-cache"
        restart: always
        expose:
            - "6379"
        networks:
            - default
        volumes:
            - redis-data:/data
            - redis-conf:/usr/local/etc/redis/redis.conf

    vdg-backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "vdg-backend"
        ports:
            - 4000:4000
        depends_on:
            - redis
        volumes:
            - .:/app
        links:
            - redis
        environment:
            - REDIS_URL=redis://redis-cache

volumes:
    redis-data:
    redis-conf:
