openapi: 3.0.0
info:
  title: HuisHelder Home Journey API
  description: API endpoints for the "Your Home Journey" feature
  version: 1.0.0
servers:
  - url: /api/v1
    description: API v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    JourneyInit:
      type: object
      required:
        - is_first_time_buyer
        - is_selling_current_home
        - has_bridge_loan
      properties:
        is_first_time_buyer:
          type: boolean
          description: Whether the user is a first-time home buyer
        is_selling_current_home:
          type: boolean
          description: Whether the user is selling their current home
        has_bridge_loan:
          type: boolean
          description: Whether the user needs a bridge loan

    Milestone:
      type: object
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
        name:
          type: string
        description:
          type: string
        order_index:
          type: integer
        is_optional:
          type: boolean

    UserMilestone:
      type: object
      properties:
        id:
          type: string
          format: uuid
        milestone:
          $ref: '#/components/schemas/Milestone'
        is_complete:
          type: boolean
        due_date:
          type: string
          format: date
        completed_at:
          type: string
          format: date-time
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/UserTask'

    UserTask:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        status:
          type: string
          enum: [PENDING, IN_PROGRESS, DONE]
        related_document_id:
          type: string
          format: uuid
          nullable: true

    Document:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
        filename:
          type: string
        file_url:
          type: string
        uploaded_at:
          type: string
          format: date-time

    FinancialSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        estimated_mortgage:
          type: number
          nullable: true
        estimated_boeterente:
          type: number
          nullable: true
        bridge_loan_needed:
          type: number
          nullable: true
        monthly_gross:
          type: number
          nullable: true
        monthly_net:
          type: number
          nullable: true

    Error:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

paths:
  /journey/init:
    post:
      tags:
        - Journey
      summary: Initialize a user's home buying journey
      description: Create or update a user's journey after onboarding
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JourneyInit'
      responses:
        '200':
          description: Journey initialized successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /journey/timeline:
    get:
      tags:
        - Journey
      summary: Get user's journey timeline
      description: Returns all user milestones sorted by order_index
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Timeline retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserMilestone'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Journey not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /journey/tasks:
    get:
      tags:
        - Journey
      summary: Get user's active tasks
      description: Returns all active tasks grouped by milestone
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Tasks retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserTask'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Journey not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /journey/tasks/{id}/complete:
    post:
      tags:
        - Journey
      summary: Mark a task as complete
      description: Marks a specific task as DONE and updates milestone status if needed
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: Task ID
      responses:
        '200':
          description: Task marked as complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found or doesn't belong to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /journey/documents/upload:
    post:
      tags:
        - Journey
      summary: Upload a document
      description: Upload a document and link to related task if applicable
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                type:
                  type: string
                  description: Document type
      responses:
        '200':
          description: Document uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Document'
        '400':
          description: No file uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /journey/finance/summary:
    get:
      tags:
        - Journey
      summary: Get financial summary
      description: Returns the financial snapshot for the user journey
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Financial summary retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/FinancialSummary'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      tags:
        - Journey
      summary: Update financial summary
      description: Updates or creates a financial summary
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                estimated_mortgage:
                  type: number
                estimated_boeterente:
                  type: number
                bridge_loan_needed:
                  type: number
                monthly_gross:
                  type: number
                monthly_net:
                  type: number
      responses:
        '200':
          description: Financial summary updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/FinancialSummary'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Journey not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
