---
django:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/server-snippet: |
        if ($request_method !~ ^(GET|POST|PUT|PATCH|DELETE|HEAD)$) {
          return 403;
        }
        add_header Cache-Control "no-store";
        add_header Pragma "no-cache";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header Content-Security-Policy "default-src 'self'; frame-src 'self' https://*.eu.pendo.io; img-src 'self' data: https://*.eu.pendo.io https://*.storage.googleapis.com; style-src 'self' 'unsafe-inline' blob: https://fonts.googleapis.com https://cdn.jsdelivr.net https://static2.sharepointonline.com https://*.eu.pendo.io https://*.storage.googleapis.com; script-src 'self' 'unsafe-inline' https://libraries.pwc.delivery https://code.jquery.com https://cdn.jsdelivr.net https://*.eu.pendo.io https://*.storage.googleapis.com; connect-src 'self'; font-src 'self' https://fonts.gstatic.com https://static2.sharepointonline.com; object-src 'none';";
    hosts:
      - host: productlegislationnavigator.stg.devcfs.com
    tls:
      - hosts:
          - productlegislationnavigator.stg.devcfs.com
        secretName: tls-certs
  podEnvItems:
    DJANGO_SETTINGS_MODULE: core.settings.stg
