# Generated by Django 4.2.13 on 2024-06-17 11:13

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Unique name of the source, e.g. the filename-YYYYMMDD', max_length=199, unique=True)),
                ('file', models.FileField(blank=True, help_text='A file field for processing in memory', null=True, upload_to='temp/', validators=[core.validators.validate_excel_and_csv_file_extension])),
                ('file_type', models.CharField(choices=[('LEGISLATION', 'LEGISLATION')], max_length=20, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='For files and other one-off sources: has it been processed?')),
                ('is_archived', models.BooleanField(default=False, help_text='Records whether the file has been copied to archive')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('process_name', models.CharField(blank=True, help_text='What is the name of the process, what does it do?', max_length=199)),
                ('level', models.CharField(choices=[('MAIN', 'MAIN'), ('SUB_PROCESS', 'SUB_PROCESS'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING')], default='MAIN', max_length=20, null=True)),
                ('is_successful', models.BooleanField(default=False, help_text='If it was completed without major errors')),
                ('is_processed', models.BooleanField(default=False, help_text='Is the processing done, even if there are errors?')),
                ('message', models.TextField(blank=True, default='', max_length=12000)),
                ('elapsed_time_minutes', models.IntegerField(blank=True, null=True)),
                ('data_source', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='datareader.datasource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
