# Generated by Django 4.2.13 on 2024-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportlog',
            name='level',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('SUB_PROCESS', 'SUB_PROCESS'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], default='MAIN', max_length=20, null=True),
        ),
    ]
