# Generated by Django 4.2.13 on 2024-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0002_alter_dataimportlog_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportlog',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
