# Generated by Django 4.2.14 on 2024-08-21 12:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datareader', '0003_dataimportlog_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='file',
            field=models.FileField(blank=True, help_text='A file field for processing in memory', null=True, upload_to='temp/', validators=[core.validators.validate_excel_and_csv_file_extension, core.validators.validate_file_size]),
        ),
    ]
