name: VDG Order App CI/CD
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
jobs:
    build:
        name: VDG Order App Pipeline Started
        runs-on: ubuntu-latest
        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Install all dependencies
              run: yarn

            - name: Compile TS -> JS /dist
              run: yarn run build:webpack

            - name: Build a Docker Image
              run: docker build .

            # - name: Login to Docker Hub
            #   uses: docker/login-action@v1
            #   with:
            #       username: ${{ secrets.DOCKERHUB_USERNAME }}
            #       password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Push to Docker Hub
            #   run: cd backend && docker push thriledlokkie983/ecommerce1-backend

            # - name: Login to Heroku Container Registry
            #   env:
            #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            #   run: cd backend && heroku container:login

            # - name: Push to Heroku
            #   env:
            #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            #   run: cd backend && heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

            # - name: Deploy the Application - (Release)
            #   env:
            #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            #   run: cd backend && heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
