# Generated by Django 4.2.13 on 2024-06-17 15:02

from datetime import datetime

from django.db import migrations, models


def populate_created_at(apps, schema_editor):
    LegislationJobRole = apps.get_model("navigator", "LegislationJobRole")
    for jobrole in LegislationJobRole.objects.all():
        jobrole.created_at = datetime(2024, 6, 17, 14, 53, 10)
        jobrole.save()


class Migration(migrations.Migration):

    dependencies = [
        ("navigator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislationjobrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(populate_created_at),
    ]
