# Generated by Django 4.2.13 on 2024-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_auto_20240617_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationjobrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
