# Generated by Django 4.2.13 on 2024-06-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0003_legislationjobrole_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislation',
            old_name='additional_link',
            new_name='additional_links',
        ),
    ]
