# Generated by Django 4.2.13 on 2024-06-26 12:49

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="preparer")
    Group.objects.get_or_create(name="approver")


class Migration(migrations.Migration):

    dependencies = [
        ("navigator", "0004_rename_additional_link_legislation_additional_links"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
