# Generated by Django 4.2.13 on 2024-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_auto_20240626_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='registration_requirements',
            field=models.ManyToManyField(blank=True, help_text='Registration requirements refer to the process of officially enrolling or recording                 certain information with a relevant authority or organization.                 It typically involves providing specific details about an individual,                 entity, or activity to establish legal recognition or compliance', related_name='registration_requirements', to='navigator.registrationrequirement', verbose_name='Registration Requirements'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='regulatory_requirements',
            field=models.ManyToManyField(blank=True, help_text='Regulatory requirements are rules, standards, or obligations established to govern                 activities or entities that must be complied with.', related_name='regulatory_requirements', to='navigator.regulatoryrequirement', verbose_name='Regulatory Requirements'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='reporting_requirements',
            field=models.ManyToManyField(blank=True, help_text='Reporting requirements are rules, or obligations on either submitting information                 to an external party such as a a relevant authority or organization, as well as                 rules or obligations on publishing information in for instance an annual statement                 or on a website', related_name='reporting_requirements', to='navigator.reportingrequirement', verbose_name='Reporting Requirements'),
        ),
    ]
