# Generated by Django 4.2.14 on 2024-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_alter_legislation_registration_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Select the date as of when the legislation is or will be first applicable', null=True, verbose_name='Effective Date'),
        ),
    ]
