# Generated by Django 4.2.14 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0007_alter_legislation_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationjobrole',
            name='non_compliance_risk',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
