# Generated by Django 4.2.14 on 2024-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_client'),
        ('navigator', '0008_legislationjobrole_non_compliance_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='background',
            field=models.TextField(blank=True, help_text="Explanation of legislation in Layman's terms", null=True, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='legislation',
            name='non_compliance_risk',
            field=models.TextField(blank=True, help_text='Explanation of the risks of not complying with the legislation', null=True, verbose_name='Risk of non-compliance'),
        ),
        migrations.AddField(
            model_name='legislation',
            name='relevant_job_role_list',
            field=models.ManyToManyField(blank=True, help_text='What job roles are relevant for this legislation', related_name='job_role_list', to='profiles.jobrole', verbose_name='Relevant list of Job Roles'),
        ),
        migrations.DeleteModel(
            name='LegislationJobRole',
        ),
    ]
