# Generated by Django 4.2.14 on 2024-08-22 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_client'),
        ('navigator', '0009_legislation_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='relevant_job_role_list',
        ),
        migrations.CreateModel(
            name='AttentionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note', models.TextField(max_length=2000)),
                ('job_role_list', models.ManyToManyField(blank=True, related_name='job_role_list', to='profiles.jobrole')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigator.legislation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
