# Generated by Django 4.2.15 on 2024-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigator", "0010_remove_legislation_relevant_job_role_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attentionpoint",
            name="constraint_identifier",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
