# Generated by Django 4.2.15 on 2024-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_client'),
        ('navigator', '0011_attentionpoint_job_roles_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='job_role_list',
            field=models.ManyToManyField(blank=True, help_text='Job roles associated with this legislation', related_name='job_role_list_legislation', to='profiles.jobrole', verbose_name='Jop role list'),
        ),
    ]
