# Generated by Django 4.2.15 on 2024-09-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0012_legislation_job_role_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='pwc_territory',
            field=models.TextField(blank=True, default=None, help_text='Add the PwC Territory which provided information about the legislation', null=True, verbose_name='PwC Territory that prepared the legislation details'),
        ),
    ]
