# Generated by Django 4.2.15 on 2024-09-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0013_legislation_pwc_territory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislation',
            old_name='summary',
            new_name='objective',
        ),
    ]
