# Generated by Django 4.2.15 on 2024-09-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0014_rename_summary_legislation_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingrequirement',
            name='refund_possibilities',
            field=models.TextField(blank=True, help_text='If applicable, a description of the possibility to request a refund and                 the applicable criteria that need to be met.', null=True, verbose_name='Refund possibilities'),
        ),
        migrations.RemoveField(
            model_name='reportingrequirement',
            name='way_of_submission',
        ),
        migrations.AddField(
            model_name='reportingrequirement',
            name='way_of_submission',
            field=models.ManyToManyField(help_text='How the requirement is fulfilled', related_name='way_of_submission', to='navigator.wayofsubmission', verbose_name='Way of Submission'),
        ),
    ]
