# Generated by Django 4.2.15 on 2024-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0015_alter_reportingrequirement_refund_possibilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingrequirement',
            name='way_of_submission',
        ),
        migrations.DeleteModel(
            name='WayOfSubmission',
        ),
        migrations.AddField(
            model_name='reportingrequirement',
            name='way_of_submission',
            field=models.TextField(blank=True, help_text='How the requirement is fulfilled', null=True, verbose_name='Way of Submission'),
        ),
    ]
