# Generated by Django 4.2.15 on 2024-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0016_remove_reportingrequirement_way_of_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportingrequirement',
            old_name='payment_obligation',
            new_name='payment_obligations',
        ),
    ]
