# Generated by Django 4.2.15 on 2024-09-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigator", "0017_rename_payment_obligation_reportingrequirement_payment_obligations"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequirement",
            name="legislation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to="navigator.legislation",
            ),
        ),
        migrations.AddField(
            model_name="regulatoryrequirement",
            name="legislation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regulatory",
                to="navigator.legislation",
            ),
        ),
        migrations.AddField(
            model_name="reportingrequirement",
            name="legislation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reporting",
                to="navigator.legislation",
            ),
        ),
    ]
