# Generated by Django 4.2.15 on 2024-09-20 13:05

from django.db import migrations


def transfer_data(apps, schema_editor):
    Legislation = apps.get_model("navigator", "Legislation")

    # Transfer data for RegistrationRequirement
    for legislation in Legislation.objects.all():
        for requirement in legislation.registration_requirements.all():
            requirement.legislation = legislation
            requirement.save()

    # Transfer data for RegulatoryRequirement
    for legislation in Legislation.objects.all():
        for requirement in legislation.regulatory_requirements.all():
            requirement.legislation = legislation
            requirement.save()

    # Transfer data for ReportingRequirement
    for legislation in Legislation.objects.all():
        for requirement in legislation.reporting_requirements.all():
            requirement.legislation = legislation
            requirement.save()


class Migration(migrations.Migration):

    dependencies = [("navigator", "0018_registrationrequirement_legislation_and_more")]

    operations = [
        migrations.RunPython(transfer_data),
    ]
