# Generated by Django 4.2.15 on 2024-09-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0019_auto_20240920_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislation',
            name='registration_requirements',
        ),
        migrations.RemoveField(
            model_name='legislation',
            name='regulatory_requirements',
        ),
        migrations.RemoveField(
            model_name='legislation',
            name='reporting_requirements',
        ),
    ]
