# Generated by Django 4.2.15 on 2024-09-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0020_remove_legislation_registration_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequirement',
            name='legislation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_requirements', to='navigator.legislation'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequirement',
            name='legislation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_requirements', to='navigator.legislation'),
        ),
        migrations.AlterField(
            model_name='reportingrequirement',
            name='legislation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_requirements', to='navigator.legislation'),
        ),
    ]
