# Generated by Django 4.2.16 on 2024-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0021_alter_registrationrequirement_legislation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='preparation_state',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('IN_REVIEW', 'IN REVIEW'), ('APPROVED', 'APPROVED')], default='CREATED', max_length=20),
        ),
    ]
