# Generated by Django 4.2.13 on 2024-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_client_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.jobrole'),
        ),
    ]
