# Generated by Django 4.2.14 on 2024-08-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_job_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
    ]
