# Generated by Django 4.2.15 on 2024-09-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_roles',
            new_name='job_role_list',
        ),
    ]
