# Generated by Django 4.2.15 on 2024-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_job_roles_profile_job_role_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tour_completed',
            field=models.BooleanField(default=False, help_text='Identifier for whether or not the user completed the guided tour'),
        ),
    ]
